config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#home'

  resources :data
  get '/intensity', to: 'users#intensity'
  get '/records', to: 'users#records'
  get '/maximum', to: 'users#maximum'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord
  scope :excercise, -> (excercise) { where excercise: excercise }
  belongs_to :user
  validates :excercise, presence: true
  validates :sets, presence: true
  validates :reps, presence: true
  validates :weight, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :data, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def create
    @data = current_user.data.new(data_params)
    @data.save
    redirect_to root_path
  end

  private
  def data_params
    params.require(:datum).permit(:excercise, :sets, :reps, :weight)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home

    @data = Datum.new
    @workoutSets = []
    @workoutReps = []
    @workoutWeight = []
    @workoutIntensity = []

    if current_user && current_user.data
      @modelData= current_user.data.all
      @modelData.each do |datum|
        @date = datum.created_at
        @intensity = datum.weight*datum.reps*datum.sets

        @workoutSets.push([@date,datum.sets])
        @workoutReps.push([@date,datum.reps])
        @workoutWeight.push([@date,datum.weight])
        @workoutIntensity.push([@date, @intensity])
      end

      @intensityData = [
          {name: "intensity", data: @workoutIntensity}
      ]
    end
  end

  def intensity

    @returned_data = 0
    @dates = []
    @intensity_array = []
    @intensities =[]
    if current_user && current_user.data.count >= 1

      (current_user.data.first.created_at.to_date..current_user.data.last.created_at.to_date).each_with_index do |date,index|
        @returned_data = 0
        current_user.data.where(created_at: date.midnight..date.end_of_day).all.each do |datum|
          @returned_data += datum.weight*datum.reps*datum.sets
        end
        @intensity_array.push([date, @returned_data])
        @dates.push(index)
        @intensities.push(@returned_data)
      end
      @intensity_data = [
          {name: "intensity", data: @intensity_array}
      ]
      @total_attendance = 0
      @all_intensity = 0
      @check =[]
      @intensity_array.each {|date, intensity|  @total_attendance += 1 if intensity > 0; @all_intensity += intensity if intensity > 0 }
      @average_attendance = (7 * @total_attendance / @intensity_array.size).round
      @all_intensity = (@all_intensity/@total_attendance).round()

      @gradient = gradient(@dates, @intensities).round()
      @gradient  = @gradient > 0 ? "+#{@gradient}" : "#{@gradient}"

    end

  end

  def records
    if current_user && current_user.data
      @collection = current_user.data.pluck(:excercise).uniq

        if @collection.include? params[:excercise_filter]
          @modelData = current_user.data.excercise(params[:excercise_filter])
          @workoutSets = []
          @workoutReps = []
          @workoutWeight = []
          @workoutIntensity = []

          @modelData.each do |datum|
            @date = datum.created_at
            @intensity = datum.weight*datum.reps*datum.sets

            @workoutSets.push([@date,datum.sets])
            @workoutReps.push([@date,datum.reps])
            @workoutWeight.push([@date,datum.weight])
            @workoutIntensity.push([@date,@intensity])
          end
          @graphData = [
              {name: "Sets", data: @workoutSets},
              {name: "Reps", data: @workoutReps},
              {name: "Weight", data: @workoutWeight},
              {name: "Intensity", data: @workoutIntensity}
          ]
         else
          @modelData= current_user.data.all
        end
    end
  end

  def maximum

    @collection = current_user.data.pluck(:excercise).uniq
    @array = @collection.to_ary
    @records = []
    @array.each do |excercise|
      @record = current_user.data.where(excercise: excercise).order(weight: :desc).first
      @records.push(@record)
    end
    @records = @records.sort_by &:excercise
  end

  def gains

  end


end

def gradient(xs,ys)
  covariance(xs,ys)/variance(xs,ys)
end

def covariance(xs,ys)
  x_column = []
  y_column = []
  xs.each_with_index { |xv,index | x_column[index] = xv - mean(xs) }
  ys.each_with_index { |yv,index | y_column[index] = yv - mean(ys) }
  yx_product = x_column.zip(y_column).map{|x,y| x*y}
  (yx_product.sum / (xs.size))
end

def variance(xs,ys)
  x_column = []
  xs.each_with_index { |xv,index | x_column[index] = (xv - mean(xs))**2 }
  x_column.sum/(xs.size)
end

def mean(values)
  "Method failed to run - values passed not an array" unless values.kind_of?(Array)
  values.sum/values.length
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper

end

app/helpers/users_helper.rb
module UsersHelper
  def intensity(datum)
    datum.sets*datum.reps*datum.weight
  end



end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#weight-mate-navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Weight Mate</a>
      </div>

    <div class="collapse navbar-collapse" id="weight-mate-navbar-collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'Daily Intensity', intensity_path  %></li>
          <li><%= link_to 'All Records', records_path  %></li>
          <li><%= link_to 'Lifting Records', maximum_path, :day => "Back"  %></li>
        </ul>
      <%end %>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% else %>

        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
        <li><%= link_to 'Edit account', edit_user_registration_path%></li>
            <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weight-mate: light workout tracker</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_include_tag 'application', 'chartkick' %>
    <%= javascript_include_tag 'application', 'highcharts' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Strap in bro!-->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/home.html.erb
<% if user_signed_in? && current_user %>
    <!--The input container for the workout-->
    <div class="row">
      <div class="col-md-4">
        <div class="panel panel-info">
          <div class="panel-heading">
            <% @collectionBack = %w[Pull-ups Pull-downs Seated-row Stack-pull Weighted-crunch Oblique-pull Oblique-twist Rotating-curl Hammer-curl] %>
            <% @collectionFront = %w[Back-squat Leg-press Leg-extension Hamstring-curl Dumbbell-bench Overhead-press Lu-raise Arnie-raise Push-down Tricep-extension] %>

              <% if current_user.data.count >= 1 %>
                <% if @collectionBack.include? current_user.data.where("created_at < ?", Time.zone.now.beginning_of_day).last.excercise %>
                    <% @collection = @collectionFront; @message = "It's leg day" %>
                <% else %>
                    <% @collection = @collectionBack; @message = "It's back day" %>
                <% end %>
              <% else %>
                <% @collection = @collectionBack; @message = "Fuck you Gerry you cunt" %>
              <% end %>

            Add an excercise - <b><%= @message %></b>
          </div>
            <div class="panel-body">
              <div class="row">
              <%= simple_form_for @data do |f| %>
                    <%= f.input :excercise, :collection => @collection, :wrapper_html => { :class => 'col-md-12' }%>
                    <div class="row">
                      <div class="col-md-12">
                        <%= f.input :sets, :wrapper_html => { :class => 'col-md-12 col-xs-4' } %>
                        <%= f.input :reps, :wrapper_html => { :class => 'col-md-12 col-xs-4' } %>
                        <%= f.input :weight, :wrapper_html => { :class => 'col-md-12 col-xs-4' } %>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <%= f.button :submit %>
                    </div>
              <% end %>
              </div>
            </div>
        </div>
      </div>


      <!--The summary portal-->

      <div class="col-md-8">
        <div class="panel panel-info">
          <div class="panel-heading">
            Your latest workout summary (This will reset tomorrow - better get to the gym!)
          </div>
          <div class="panel-body">
            <% if current_user.data.count >= 1 %>
                <table class="table table-responsive">
                  <tr>
                    <th>Excercise</th>
                    <th>Sets</th>
                    <th>Reps</th>
                    <th>Weight</th>
                    <th>Intensity</th>
                  </tr>
                  <% @totalIntensity = 0   %>
                  <% @modelData.where("created_at >= ?", Time.zone.now.beginning_of_day).each do |datum| %>
                      <tr>
                        <td><%= datum.excercise %></td>
                        <td><%= datum.sets %></td>
                        <td><%= datum.reps %></td>
                        <td><%= datum.weight %></td>
                        <td><%= intensity(datum) %></td>
                        <% @totalIntensity += intensity(datum) %>
                      </tr>
                  <% end %>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>Total:</th>
                    <td><%= @totalIntensity %></td>
                  </tr>
                </table>
            <% else %>
                <p>Create some data to get started</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/users/intensity.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        Intensity of your workouts - The <b>summed by day</b> dot product of repetitions, sets and the weight lifted
      </div>
      <div class="panel-body">
        <% if current_user.data.count >= 1 %>
            <%= line_chart @intensity_data %>
        <% else %>
            <p>Create some data to get started</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        Average attendance:
      </div>
      <div class="panel-body text-center">
        <% if current_user.data.count >= 1 %>
          <h1><b><%=@average_attendance%></b><small> Days a week</small></h1>
        <% else %>
            <p>Create some data to get started</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        Average intensity:
      </div>
      <div class="panel-body text-center">
        <% if current_user.data.count >= 1 %>
            <h1><b><%=@all_intensity%></b></h1>
        <% else %>
            <p>Create some data to get started</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        Intensity trend:
      </div>
      <div class="panel-body text-center">
        <% if current_user.data.count >= 1 %>
            <h1><b><%=@gradient%><small> / day</small></b></h1>
        <% else %>
            <p>Create some data to get started</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/maximum.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        Maximum weights lifted
      </div>
      <div class="panel-body">

        <table class="table table-responsive">
          <tr>
            <th>Excercise</th>
            <th>Weight (kg)</th>

          </tr>
          <% @totalIntensity = 0   %>
          <% @records.each do |datum| %>
              <tr>
                <td><%= datum.excercise %></td>
                <td><%= datum.weight %></td>
              </tr>
          <% end %>

        </table>

      </div>
    </div>
  </div>
</div>

app/views/users/records.html.erb
<% if current_user.data.count >= 1 && @graphData.present? %>
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-info">
          <div class="panel-heading">
            <b><%= params[:excercise_filter] %>: Sets/Reps/Weight</b>
          </div>
          <div class="panel-body">
            <%= line_chart @graphData[0..2] %>

          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-info">
          <div class="panel-heading">
            <b><%= params[:excercise_filter] %>: Intensity</b>
          </div>
          <div class="panel-body">

            <%= line_chart @graphData[3..3], colors: ["orange", "#999"] %>
          </div>
        </div>
      </div>
    </div>
<% else %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
            <%= simple_form_for '', :method => :get do |f| %>
                <%= f.input :excercise_filter, label: false , :collection => @collection, :selected => params[:excercise_filter],
                            :include_blank => "(select if none)", :required => false %>
                <%= f.button :submit, 'Filter' %>
            <% end %>

          </div>
        </div>

      </div>
      <div class="panel-body">
        <% if current_user.data.count >= 1 && params[:excercise_filter].present? %>
            <table class="table table-responsive">
              <tr>
                <th>Sets</th>
                <th>Reps</th>
                <th>Weight</th>
                <th>Intensity</th>
                <th>Date</th>
              </tr>
              <% @totalIntensity = 0   %>
              <% @modelData.each do |datum| %>
                  <tr>
                    <td><%= datum.sets %></td>
                    <td><%= datum.reps %></td>
                    <td><%= datum.weight %></td>
                    <td><%= intensity(datum) %></td>
                    <td><%= datum.created_at.to_date %></td>
                    <% @totalIntensity += intensity(datum) %>
                  </tr>
              <% end %>

            </table>
        <% else %>
            <p>Select a filter above</p>
        <% end %>
      </div>
    </div>
  </div>
</div>